@version: 4.11
@include "scl.conf"

# Enforce IPv4 and TCP to ensure guaranteed packet delivery
source s_network {
    network(
        ip("127.0.0.1")
        transport("tcp")
        port(5140)
    );
};

# The Destination
destination d_kafka {
    kafka-c(
        bootstrap-servers("127.0.0.1:9092")
        topic("logs_raw")
        message("{\"timestamp\": \"$ISODATE\", \"source_ip\": \"$SOURCEIP\", \"destination_ip\": \"localhost\", \"event_type\": \"Live Network Event\", \"severity\": \"$PRIORITY\", \"raw_message\": \"$MSG\", \"user_agent\": null}")
    );
};

# The Pipeline
log {
    source(s_network);
    destination(d_kafka);
};